sudo: required
dist: trusty
before_install:
- wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
- sudo ./install-tl-ubuntu
- sudo tex -v
- sudo mkdir -p /usr/share/fonts/opentype/
- sudo mv ./fonts/AdobeFangsongStd-Regular.otf /usr/share/fonts/opentype/
- sudo mv ./fonts/AdobeHeitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
- sudo mv ./fonts/AdobeKaitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
- sudo mv ./fonts/AdobeSongStd-Light\ \(v5.010\).otf /usr/share/fonts/opentype/
- sudo mkfontscale
- sudo mkfontdir
- sudo fc-cache -fv
- fc-list :lang=zh
- sudo wget http://mirrors.ctan.org/macros/latex/contrib/minted.zip
- sudo unzip minted.zip
- cd minted/
- sudo make
- sudo mv minted.sty /usr/share/texlive/texmf-dist/tex/latex/minted
- sudo mv minted1.sty /usr/share/texlive/texmf-dist/tex/latex/minted
- cd ..
- sudo apt-get install python-pygments
script:
- cd Analysis_TCP_in_Linux/
- make
after_script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && exit 0'
- make clean
- git add tcp.pdf
- git commit -m "[travis-ci] auto generate tex.pdf" 
- git push --force --quiet "https://${GH_TOKEN}@github.com/fzyz999/Analysis_TCP_in_Linux" master:master
